site_name: commonplace-book-explorer
repo_url: https://github.com/willf/commonplace-book-explorer
site_url: https://willf.github.io/commonplace-book-explorer
site_description: Commonplace Book Explorer
site_author: Will Fitzgerald
edit_uri: edit/main/docs/
repo_name: willf/commonplace-book-explorer
copyright: Maintained by <a href="https://willf.com">willf</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/commonplace_book_explorer"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/willf/commonplace-book-explorer
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/commonplace-book-explorer

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
